// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaJCxxfkVGElc1nORiDC1Be92q3k98CFg',
    appId: '1:320766440190:web:5b97280a725d1f64842baf',
    messagingSenderId: '320766440190',
    projectId: 'vip-lounge-f3730',
    authDomain: 'vip-lounge-f3730.firebaseapp.com',
    storageBucket: 'vip-lounge-f3730.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGc13W0AXOVu6z8dB_dyyndZw_oxKSIxc',
    appId: '1:320766440190:android:9d8801c42a7d9cc0842baf',
    messagingSenderId: '320766440190',
    projectId: 'vip-lounge-f3730',
    storageBucket: 'vip-lounge-f3730.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsWZEujXS0Kk5Ua2QCozfVnrsT4NrwD1c',
    appId: '1:320766440190:ios:fbb35c9873c09977842baf',
    messagingSenderId: '320766440190',
    projectId: 'vip-lounge-f3730',
    storageBucket: 'vip-lounge-f3730.firebasestorage.app',
    iosBundleId: 'com.example.vipLounge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsWZEujXS0Kk5Ua2QCozfVnrsT4NrwD1c',
    appId: '1:320766440190:ios:fbb35c9873c09977842baf',
    messagingSenderId: '320766440190',
    projectId: 'vip-lounge-f3730',
    storageBucket: 'vip-lounge-f3730.firebasestorage.app',
    iosBundleId: 'com.example.vipLounge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaJCxxfkVGElc1nORiDC1Be92q3k98CFg',
    appId: '1:320766440190:web:564b28218b30cdf9842baf',
    messagingSenderId: '320766440190',
    projectId: 'vip-lounge-f3730',
    authDomain: 'vip-lounge-f3730.firebaseapp.com',
    storageBucket: 'vip-lounge-f3730.firebasestorage.app',
  );
}
